name: Build and Test Flask App

on: [push, pull_request]

jobs:
  flask-ci-lab:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flask-ci-lab

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run container
        run: docker run -d -p 5000:5000 --name test-container flask-app

      - name: Install test dependencies
        run: pip install requests

      - name: Wait for container to start
        run: sleep 5

      - name: Run tests
        run: python3 tests/test_app.py

      - name: Cleanup
        run: docker rm -f test-container
